### ISSUE TITLE
Deploy missing

### ISSUE THREAD

**Issue by axeberg** [chas-academy/04-todo-app-jdp2018#1]
@jdp2018 ping me back when closing this issue and let me know when this is deployed and ready to be graded.

**Comment by Pinones** [comment]
@axelolsson deployed.

**Comment by axeberg** [comment]
@jdp2018 Deploy is showing errors

**Comment by axeberg** [comment]
Sorry, keep pressing the wrong button on my phone. This is still an issue.

**Comment by Pinones** [comment]
@axelolsson  I  accidentally destroyed the server, it's up now.
